### ISSUE TITLE
Deploying functions and API separately

### ISSUE THREAD

**Issue by gpoitch** [bustle/shep#296]
Currently `shep deploy` will "Deploy both functions and APIs to AWS".

I would like to be able to deploy my functions separately, with a different alias that is not the name of the environment.  

For example, my API (and functions) can currently be deployed to 'production' like this:
```
shep deploy --env production
```

I would like to also publish a separate function alias without having to create a new API stage (theoretical command):
```
shep deploy-functions --alias 774f0a4
```

This way, I could invoke different lambda function versions from my production stage API. (e.g. through a query string/stage variable mapping)
`https://production.api-example.com?version=774f0a4`

**Comment by southpolesteve** [comment]
I want this too :) I think the easiest thing may be to add a `--no-api` flag to `deploy`. We kind of handle that case now when the user does not have an `api.json` file

**Comment by gpoitch** [comment]
Works for me
