### ISSUE TITLE
Require API Key

### ISSUE THREAD

**Issue by jonhewines** [bustle/shep#312]
Hi

Thanks for this project, it is really simplifying our workflow.

Is there a way to require an API key for an endpoint? It is difficult to set them through the web console, because the API get over-written when we re-deploy from shep

Thanks!

**Comment by southpolesteve** [comment]
@jonhewines API keys don't have explicit support in shep but you should be able to make it work. After you make and deploy a change in the AWS Console, use `shep pull` to copy a JSON representation of your API config to the file `api.json` and make sure it is checked into git. Shep references that file directly when deploying API gateway

**Comment by jonhewines** [comment]
@southpolesteve thanks for the feedback. In case anyone else is looking for this, I made it work by adding the following to each endpoint's definition in `api.json`:

```
"security": [
          {
            "api_key": []
          }
]
```

For example:

```
"post": {
        "x-amazon-apigateway-integration": {
          "uri": "arn:xxxxxxxxxxxxxxxx",
          "passthroughBehavior": "when_no_match",
          "httpMethod": "POST",
          "type": "aws_proxy"
        },
        "security": [
          {
            "api_key": []
          }
        ]
      }
```

Additionally, the following is required as the last element of the `api.json` object file, and works globally for all endpoints in the project:

```
"securityDefinitions": {
    "api_key": {
      "type": "apiKey",
      "name": "x-api-key",
      "in": "header"
    }
  }
```

Thanks again!
